name: QA AI Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qa-ai:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Run QA AI Analysis
        uses: webisoftSoftware/qalia@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_url: 'http://localhost:8080'
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          max_depth: 3
          timeout: 300
          headless: true
          frameworks: 'playwright,cypress,jest'
          output_dir: 'qalia-tests'
          # Optional: Add any specific configuration for the demo web app
          # max_pages: 10
          # config_file: qalia-config.yml 