name: QA AI Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  qa-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GITHUB }}

      - name: Run QA AI analysis
        run: |
          echo "🚀 Running QA AI analysis..."
          docker run --rm \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e INPUT_APP_URL=${{ secrets.APP_URL }} \
            -e INPUT_MAX_DEPTH=2 \
            -e INPUT_TIMEOUT=30000 \
            -e INPUT_HEADLESS=true \
            -e INPUT_FRAMEWORKS=react \
            -e INPUT_OUTPUT_DIR=/app/output \
            -e GITHUB_STEP_SUMMARY=/app/output/summary.md \
            -v ${{ github.workspace }}/output:/app/output \
            ghcr.io/webisoftsoftware/qalia:main 