name: "\U0001F916 Qalia Generated Tests"
'on':
  repository_dispatch:
    types:
    - qalia-test-matrix
  pull_request:
    branches:
    - main
    - master
    - develop
    paths-ignore:
    - qalia-tests/**
    - .github/workflows/qalia-*.yml
  push:
    branches:
    - main
    - master
    paths-ignore:
    - qalia-tests/**
    - .github/workflows/qalia-*.yml
  workflow_dispatch: null
jobs:
  test-matrix:
    name: Test ${{ matrix.framework }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '\U0001F916 Add Qalia generated\
      \ tests and workflows') && !contains(github.event.head_commit.author.name, 'Qalia\
      \ AI')"
    strategy:
      fail-fast: false
      matrix:
        framework:
        - playwright
        - cypress
        - jest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.client_payload.commit_sha || github.sha }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Check if framework tests exist
      id: check-tests
      run: "\n                                if [ -d \"qalia-tests/${{ matrix.framework\
        \ }}\" ] && [ -f \"qalia-tests/${{ matrix.framework }}/package.json\" ]; then\n\
        \                                    echo \"exists=true\" >> $GITHUB_OUTPUT\n\
        \                                    echo \"\u2705 ${{ matrix.framework }}\
        \ tests found\"\n                                else\n                  \
        \                  echo \"exists=false\" >> $GITHUB_OUTPUT\n             \
        \                       echo \"\u26A0\uFE0F ${{ matrix.framework }} tests\
        \ not found\"\n                                fi\n                      \
        \      "
    - name: Install dependencies
      if: steps.check-tests.outputs.exists == 'true'
      run: cd qalia-tests/${{ matrix.framework }} && npm ci
    - name: Install Playwright browsers
      if: steps.check-tests.outputs.exists == 'true' && matrix.framework == 'playwright'
      run: cd qalia-tests/playwright && npx playwright install --with-deps
    - name: Run tests
      if: steps.check-tests.outputs.exists == 'true'
      run: "\n                                cd qalia-tests/${{ matrix.framework\
        \ }}\n                                case \"${{ matrix.framework }}\" in\n\
        \                                  \"playwright\")\n                     \
        \               npx playwright test\n                                    ;;\n\
        \                                  \"cypress\")\n                        \
        \            npx cypress run\n                                    ;;\n   \
        \                               \"jest\")\n                              \
        \      npm test\n                                    ;;\n                \
        \                esac\n                            "
      env:
        CI: 'true'
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always() && steps.check-tests.outputs.exists == 'true'
      with:
        name: ${{ matrix.framework }}-results
        path: qalia-tests/${{ matrix.framework }}/test-results/
