name: "\U0001F332 Qalia Cypress Tests"
'on':
  repository_dispatch:
    types:
    - qalia-test-cypress
  pull_request:
    branches:
    - main
    - master
    - develop
  push:
    branches:
    - main
    - master
  workflow_dispatch: null
jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.client_payload.commit_sha || github.sha }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: npm
        cache-dependency-path: qalia-tests/cypress/package-lock.json
    - name: Check if tests exist
      id: check-tests
      run: "\n                                if [ -d \"qalia-tests/cypress\" ] &&\
        \ [ -f \"qalia-tests/cypress/package.json\" ]; then\n                    \
        \                echo \"exists=true\" >> $GITHUB_OUTPUT\n                \
        \                    echo \"\u2705 Cypress tests found\"\n               \
        \                 else\n                                    echo \"exists=false\"\
        \ >> $GITHUB_OUTPUT\n                                    echo \"\u26A0\uFE0F\
        \ Cypress tests not found - skipping\"\n                                fi\n\
        \                            "
    - name: Install dependencies
      if: steps.check-tests.outputs.exists == 'true'
      run: cd qalia-tests/cypress && npm ci
    - name: Run Cypress tests
      if: steps.check-tests.outputs.exists == 'true'
      run: cd qalia-tests/cypress && npx cypress run
      env:
        CI: 'true'
    - name: Upload Cypress Screenshots
      uses: actions/upload-artifact@v4
      if: failure() && steps.check-tests.outputs.exists == 'true'
      with:
        name: cypress-screenshots
        path: qalia-tests/cypress/cypress/screenshots
    - name: Upload Cypress Videos
      uses: actions/upload-artifact@v4
      if: always() && steps.check-tests.outputs.exists == 'true'
      with:
        name: cypress-videos
        path: qalia-tests/cypress/cypress/videos
