- name: Run Playwright test
  working-directory: qalia-tests/playwright
  run: |
    echo "Current directory: $(pwd)"
    echo "Files in directory:"
    ls -la
    
    # Create config if it doesn't exist
    if [ ! -f "playwright.config.ts" ] && [ ! -f "playwright.config.js" ]; then
      echo "Creating minimal Playwright config..."
      cat > playwright.config.ts << 'EOF'
    import { defineConfig, devices } from '@playwright/test';

    export default defineConfig({
      testDir: '.',
      timeout: 30000,
      projects: [
        { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
        { name: 'firefox', use: { ...devices['Desktop Firefox'] } },
        // WebKit disabled due to missing system dependencies in GitHub Actions
      ],
      use: {
        headless: true,
        viewport: { width: 1280, height: 720 },
        ignoreHTTPSErrors: true,
      },
    });
    EOF
    fi
    
    # Extract just the filename if the path includes the directory structure
    TEST_FILE="${{ github.event.inputs.test_file }}"
    if [[ "$TEST_FILE" == qalia-tests/playwright/* ]]; then
      TEST_FILE="${TEST_FILE#qalia-tests/playwright/}"
    fi
    
    echo "Running test file: $TEST_FILE"
    npx playwright test "$TEST_FILE" --reporter=json
